CREATE TABLE item_type (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE set (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  item_type_id INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (item_type_id) REFERENCES item_type(id)
);

CREATE TABLE item (
  id SERIAL PRIMARY KEY,
  set_id INTEGER NOT NULL,
  character VARCHAR(50) NOT NULL,
  alternate_form VARCHAR(50) NOT NULL,
  readings VARCHAR(255),
  meaning VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (set_id) REFERENCES sets(id)
);